service: myapp${{env:SERVERLESS_SERVICE_SUFFIX, ''}}
provider:
  name: aws
  stackName: ${{self:service}}-${{self:provider.stage}}
  runtime: nodejs14.x
  memorySize: 1024
  timeout: 6
  logRetentionInDays: ${{self:custom.stages.${{self:provider.stage}}.logRetentionInDays}}
  stage: ${{opt:stage, env:NODE_ENV, 'development'}}
  profile: ${{self:custom.stageConfig.profile}}
  region: ap-southeast-2
  variableSyntax: "\\${{([ ~:a-zA-Z0-9._@\\'\",\\-\\/\\(\\)]+?)}}"
  logs:
    restApi:
      format: '{ "requestId":"$context.requestId", "ip": "$context.identity.sourceIp", "caller":"$context.identity.caller", "user":"$context.identity.user", "requestTime":"$context.requestTime", "httpMethod":"$context.httpMethod", "resourcePath":"$context.resourcePath", "status":"$context.status", "protocol":"$context.protocol", "responseLength":"$context.responseLength" }'
      level: INFO # TODO: add custom field for setting this; default to ERROR for prod
    # Enable connection reuse for AWS SDK for instant performance boost
    # https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/node-reusing-connections.html
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
  cors: true

package:
  individually: true

plugins:
  - serverless-dotenv-plugin
  - serverless-domain-manager
  - serverless-prune-plugin
  - serverless-plugin-tracing
  - serverless-iam-roles-per-function
  - serverless-webpack
  - serverless-stack-output
  - serverless-cloudside-plugin
  - serverless-plugin-aws-alerts
  - '../../../../serverless-amplify-plugin'
  # - '@brettstack/serverless-amplify-plugin'
  - serverless-offline
  - serverless-stack-termination-protection
  - serverless-plugin-modularize

custom:
  stages:
    development:
      profile: myapp_dev
      logRetentionInDays: 1
      amplify:
      api:
        domainEnabled: false
      alarms:
        notificationEmail: ${{env:ALARMS_NOTIFICATION_EMAIL}}
    staging:
      profile: myapp_staging
      logRetentionInDays: 3
      api:
        domainEnabled: false
        domainName: staging.api.example.com
        validationDomain: example.com
      amplify:
        # domainName: staging.example.com
        # branch: staging
      alarms:
        notificationEmail: alert@example.com
    production:
      profile: myapp_prod
      logRetentionInDays: 14
      deletionPolicy: Retain
      pointInTimeRecoveryEnabled: true
      api:
        domainEnabled: false
        domainName: api.example.com
        validationDomain: example.com
      amplify:
        # domainName: example.com
      alarms:
        notificationEmail: alert@example.com
  stageConfig: ${{self:custom.stages.${{self:provider.stage}}}}
  deletionPolicy: ${{self:custom.stageConfig.deletionPolicy, 'Delete'}}
  prune:
    automatic: true
    number: 10
  customDomain:
    domainName: ${{self:custom.stageConfig.api.domainName, ''}}
    certificateName: ${{self:custom.stageConfig.api.domainName, ''}}
    enabled: ${{self:custom.stageConfig.api.domainEnabled, false}}
    # createRoute53Record: ${{self:custom.stageConfig.api.isDomainRoute53, false}}
  serverless-offline:
    httpPort: 4911
    noPrependStageInUrl: true
  amplify:
    isManual: true
    addNextPageRedirects: true
    domainName: ${{self:custom.stageConfig.amplify.domainName, ''}}
    buildSpecValues:
      artifactBaseDirectory: packages/ui/out
      preBuildWorkingDirectory: packages/ui
    buildCommandEnvVars:
      prefix: 'NEXT_PUBLIC_'
      allow:
        - ApiEndpoint
        - CognitoIdentityPoolId
        - CognitoUserPoolId
        - CognitoUserPoolClientId
        - Region
  webpack:
    webpackConfig: ./functions.webpack.config.js
  output:
    file: ./stack-outputs.${{self:provider.stage}}.json
    handler: stack-outputs.handler
  alerts:
    dashboards: false
    nameTemplate: $[functionName]-$[metricName]-Alarm
    topics:
      alarm:
        topic: ${{self:service}}-${{self:provider.stage}}-alarm
        notifications:
          - protocol: email
            endpoint: ${{self:custom.stageConfig.alarms.notificationEmail}}
    # TODO: Add short and long alarms for each
    alarms:
      - functionThrottles
      - functionErrors
      - functionInvocations
      - functionDuration
  serverlessTerminationProtection:
    stages:
      - staging
      - production
  modularize:
    glob: 'serverless-templates/**/*.yaml'
    
resources:
  Conditions:
    IsApiCustomDomainEnabled:
      !Equals
        - ${{self:custom.customDomain.enabled}}
        - true
  
  Resources:
    AcmCertificate:
      Type: AWS::CertificateManager::Certificate
      Condition: IsApiCustomDomainEnabled
      Properties:
        DomainName: ${{self:custom.customDomain.domainName}}
        DomainValidationOptions:
          - DomainName: ${{self:custom.customDomain.domainName}}
            ValidationDomain: ${{self:custom.stageConfig.api.validationDomain, ''}}

    # Due to a Serverless Framework bug, we need to create our own Authorizer, instead of
    # simply specifying `authorizer.arn: !GetAtt CognitoUserPool.Arn` in the function.
    # https://github.com/serverless/serverless/issues/3212#issuecomment-450574093
    ApiGatewayAuthorizer:
      DependsOn:
        - ApiGatewayRestApi
      Type: AWS::ApiGateway::Authorizer
      Properties:
        Name: CognitoAuthorizer
        IdentitySource: method.request.header.Authorization
        RestApiId:
          Ref: ApiGatewayRestApi
        Type: COGNITO_USER_POOLS
        ProviderARNs:
          - !GetAtt CognitoUserPool.Arn
  Outputs:
    ApiEndpoint:
      Value: !Sub https://${ApiGatewayRestApi}.execute-api.${AWS::Region}.amazonaws.com/${{self:provider.stage}}